### ISSUE TITLE
Unlimited taps on guess after guessing a number

### ISSUE THREAD

**Issue by Suryansh987** [C-o-m-o-n/numQuest#4]
![issue-image](https://github.com/C-o-m-o-n/numQuest/assets/128071297/ef953399-80c0-4261-9997-83114f4f8b6f)
As i guessed the Number in first attempt and tap on guess again. It guesses the same number again and keep increasing the attempts and score. It will be better if it asks user to guess another number and then increment the score if user guessed it write. 
i.e: guess button should be allowed to tap only once for single guess

Another suggestion to set initial score at 0 and show the score after guessing the number correctly.

**Comment by C-o-m-o-n** [comment]
thanks for the suggestion @Suryansh987 , we'll look into it

**Comment by Suryansh987** [comment]
Thanks , fixed the issue in Pull Request. Closing the Issue

**Comment by C-o-m-o-n** [comment]
> Thanks , fixed the issue in Pull Request. Closing the Issue

Thanks, do you mind joining discord channel for easier communication with other contributors?
https://discord.gg/9SQZUGFW
